In [2]:
import numpy as np

**Задача 1.** Аналитик собрал статистику за 36 прошедших месяцев, согласно которой вложение в акцию компании АВС позволило за месяц заработать 15% в 1 случае из 36 проанализированных месяцев, 10% - в 2 случаях, 5% - в 3 случаях, 0% в 23 случаях, потерять 5% в 6 случаях, и потерять 10% в оставшихся случаях. Определить ожидаемое значение доходности инвестиции.

Ожидаемое значение доходности инвестиции определим по формуле:

$$E = \sum_{i=1}^{n} R_{i} \cdot P_{i}, где:$$

$R_{i}$ - значение i доходности, <br>
$P_{i}$ - вероятность получения доходности $R_{i}$, <br>
$n$ - количество потенциальных значений доходности

In [ ]:
r_i = np.array([0.15, 0.10, 0.05, 0.00, -0.05, -0.10])
p_i = np.array([1/36, 2/36, 3/36, 23/36, 6/36, 1/36])

In [ ]:
E = np.sum(r_i*p_i)
print(round(M*100, 2))

0.28


**Ответ:** Ожидаемое значение доходности инвестиции: 0.28 %

**Задача 2.** Инвестиционный фонд за 7 предыдущих лет заработал следующие годовые доходности: +5%; -2%; +12%; +7%; -4%; +11%; +9%. Если предположить, что в среднем фонд будет зарабатывать такую же доходность, как и по итогам прошедших 7 лет (в смысле геометрической доходности), и вложить $100 тыс. в этот фонд, то какой ожидаемый результат будет через 5 лет?

Определим среднюю доходность инвестиционного фонда за период в n лет (n = 7 лет) по формуле:
$$Ravg = \left( \prod_{t=1}^{n} (1 + r_i) \right)^{1/n} - 1, где: $$

$r_i$ - доходность за год в i год, <br>
n - число лет,<br>
$\prod_{t=1}^{n}$ - знак произведения; он говорит нам о том, что перемножаются годы с доходностями, начиная от $r_1$ до $r_n$.



In [ ]:
n0 = 7
r_i=np.array([0.05, -0.02, 0.12, 0.07, -0.04, 0.11, 0.09])

In [ ]:
Ravg=(np.prod(1+r_i)) ** (1/n0) - 1
print(round(Ravg, 4))

0.0527


Ожидаемый результат (будующая доходность) инвест.фонда через 5 лет (n = 5) определим по формуле:

$$FVfund= PVfund * (1 + Ravg) ^ n, где: $$

$PVfund$ - текущая стоимость инвестиций, <br>
$Ravg$ - средняя доходность инвест. фонда в доли ед., <br>
$n$ - интервал времени, количество лет

In [ ]:
PVfund = 100000
n1 = 5

In [ ]:
FVfund = PVfund*(1 + Ravg) ** n1
print(round(FVfund, 2))

129257.46


**Ответ:** Ожидаемый результат (будующая доходность) инвест.фонда через 5 лет  составит: 129 257.46 $

**Задача 3.** В инвестиционном анализе есть т.н. показатель Шарпа, который характеризует эффективность инвестиции в фонд. Он рассчитывается как отношение средней доходности к риску (волатильности). Рассчитайте этот коэффициент для условий задачи 2.

Коэффициент Шарпа определим по формуле:

$$S = \frac{Ravg}{\sigma}, где: $$

где:

- $Ravg$ - геометрическое среднее годовых доходностей (из задачи №2 Ravg = 5.27%)
- $\sigma$ - стандартное отклонение доходности портфеля

In [ ]:
Ravg = 5.27
sigma = np.std(r_i, ddof=1) * 100

In [ ]:
print(round(sigma, 2))

6.24


In [ ]:
S = Ravg / sigma
print(round(S, 2))

0.84


**Ответ:** Коэффициент Шарпа равен 0.84

**Задача 4.** Компания по страхованию автомобилей разделяет водителей по трем категориям в зависимости от опыта: категория 1 (стаж вождения более 10 лет), категория 2 (стаж более 2 лет, но меньше 10), категория 3 (стаж менее 2 лет). Для данной компании среди 100% застрахованных 30% принадлежат категории 1, 50% – категории 2, 20% – категории 3. Вероятность того, что в течение года водитель категории 1 попадет хотя бы в одно ДТП равна 1%; для водителя категории 2 - 3%, а для водителя категории 3 – 10%. Клиент компании застраховал автомобиль и попал в ДТП. Какова вероятность того, что он относится к категории 1?

Воспользуемся теоремой Байеса, которая  описывает вероятность события А на основе информации о некоторых условиях В, которые связаны
с наступлением события:

$$P(A|B) = \frac{P(A1) * P(B|A1)}{P(B)}, где: $$

P(A|B) - вероятность того, что водитель относится к категории 1, если он попал в ДТП; <br>
P(A) - вероятность того, что водитель относится к категории 1;<br>
P(B|A) - вероятность того, что водитель попал в ДТП, если он относится к категории 1;<br>
P(B) - общая (полная) вероятность попадания в ДТП, определим по следующей формуле:<br>

$$P(B) =  P(B|A1) * P(A1) + P(B|A2) * P(A2) + P(B|A3) * P(A3)$$

In [ ]:
P_BA1 = 0.01
P_BA2 = 0.03
P_BA3 = 0.10
P_A1 = 0.3
P_A2 = 0.5
P_A3 = 0.2

In [ ]:
P_B = P_BA1 * P_A1 + P_BA2 * P_A2 + P_BA3 * P_A3
print(round(P_B, 3))

0.038


In [ ]:
P_AB = (P_A1 * P_BA1) / P_B
print(round(P_AB, 3) * 100)

7.9


**Ответ:** Вероятность того, что водитель, попавший в ДТП, относится к категории 1, составляет 7.9%.

**Задача 5.** Аналитик собрал статистические данные между ценой акции перерабатывающей компании и ценой ресурса, который эта компания перерабатывает:<br>
Месяц 1 2 3 4 5 6 7 8 9 10 11 12<br>
Цена акции, в долларах: 12,1 15,2 15,3 15,7 15,2 16,1 16,5 17,1 17,2 17,0 16,8 16,9<br>
Цена ресурса, в долларах: 115,0 119,0 121,0 130,0 131,0 150,0 155,0 172,0 174,0 168,0 161,0 159,0<br>
И предположил, что цена акции зависит от цены ресурса с задержкой на 1 месяц. Определить уравнение регрессии для этого предположения и сделать на его основе прогноз цены акции на 13 месяц.

Для того, чтобы сделать прогноз цены акции на 13 месяц, воспользуемся методом
наименьших квадратов для линейной регрессии.
По методу наименьших квадратов первоначально определяем вид предполагаемой зависимости, простейшая модель зависимости y = f(x) это линейная модель, когда:<br> $$y = a + bx, где: $$

y - цена акции;<br>
x- цена ресурса с задержкой на 1 месяц;<br>
a и b - коэффициенты регрессии (неизвестные параметры).

Для нахождения коэффициентов a и b, воспользуемся  следующими формулами:

$$b = \frac{n \sum_{i=1}^n (x_i y_i) - \sum_{i=1}^n x_i \sum_{i=1}^n y_i}{n \sum_{i=1}^n x_i^2 - (\sum_{i=1}^n x_i)^2}$$

$$a = \frac{\sum_{i=1}^n y_i - b \sum_{i=1}^n x_i}{n}$$

In [8]:
stock_prices = np.array([12.1, 15.2, 15.3, 15.7, 15.2, 16.1, 16.5, 17.1, 17.2, 17.0, 16.8, 16.9])
resource_prices = np.array([115.0, 119.0, 121.0, 130.0, 131.0, 150.0, 155.0, 172.0, 174.0, 168.0, 161.0, 159.0])

Предполагаем задержку в 1 месяц:

In [7]:
resource_prices_moved = resource_prices[:-1]
stock_prices_moved = stock_prices[1:]
n = len(resource_prices_moved)

Найдем коэффициенты a и b:

In [20]:
b = (n * np.sum(resource_prices_moved * stock_prices_moved) - np.sum(resource_prices_moved) * np.sum(stock_prices_moved)) / (n * np.sum(resource_prices_moved**2) - np.sum(resource_prices_moved)**2)
a = (np.sum(stock_prices_moved) - b * np.sum(resource_prices_moved)) / n
print((round(a,2)), (round(b,2)))

11.47 0.03


Прогноз цены акции на 13 месяц:

In [10]:
predicted_stock_price = a + b * resource_prices[-1]
print(round(predicted_stock_price, 2))

16.73


**Ответ:** Прогноз цены акции на 13 месяц составляет: 16.73 $